<?php require_once("templates/header.phtml") ?>

<?php if ($verify): ?>
    <?php require_once("templates/formAutores.phtml") ?>
<?php endif ?>

<div class="container-listado">
    <table class="table table-dark">
        <thead>
            <tr>
                <th scope="col">Nombre</th>
                <th scope="col">Edad</th>
                <th scope="col">Nacionalidad</th>
                <?php if ($verify): ?>
                    <th scope="col">Acciones</th>
                <?php endif ?>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($autor as $item): ?>
                <tr>
                    <td><?= $item->Nombre ?></td>
                    <td><?= $item->Edad ?></td>
                    <td><?= $item->Nacionalidad ?></td>
                    <?php if ($verify): ?>
                        <td>
                            <a href="eliminarAutor/<?= $item->id_autor ?>" type='button' class='btn btn-danger'>Eliminar</a>
                            <form action="formModificarAutor/<?= $item->id_autor ?>" method="POST" style="display: inline;">
                                <button type="submit" class="btn btn-success">Modificar</button>
                            </form>
                        </td>
                    <?php endif ?>
                </tr>
            <?php endforeach ?>
        </tbody>
    </table>
</div>
