<?php require_once("templates/header.phtml") ?>


<div class="container-listado">
    <div class="contenedor-imagen-libro">
    <img class="imagen-libro" src="<?= $libro->imagen ?>">
    </div>
    <ul class='list-group'>
        <li class='list-group-item list-group-item-dark'> Título: <?= $libro->Titulo ?>
        </li>
        <li class='list-group-item list-group-item-dark'> Saga: <?= $libro->Saga ?>
        </li>
        <li class='list-group-item list-group-item-dark'> Género: <?= $libro->Genero ?>
        </li>
    </ul>
    <a href="showLibros" class="btn btn-primary">Back</a>
</div>
