<?php require_once("templates/header.phtml") ?>

<div class="form-container">
  <?php if ($libro && $verify): ?>
    <form action="<?= BASE_URL ?>modificarLibro/<?= $libro['id_libros'] ?>" method="POST" class="my-4">
      <div class="row">
        <div class="col-9">
          <div class="form-group">
            <label>Modificar autor:</label>
            <select name="id_autor" class="form-control">
              <option value="">Elegir</option>
              <?php foreach ($autores as $autor): ?>
                <option value="<?= $autor->id_autor ?>"> <?= $autor->Nombre ?> </option>
              <?php endforeach ?>
            </select>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-9">
          <div class="form-group">
            <label>Modificar título</label>
            <input name="titulo" type="text" class="form-control" value="<?= $libro['Titulo'] ?>">
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-9">
          <div class="form-group">
            <label>Modificar saga</label>
            <input name="saga" type="text" class="form-control" value="<?= $libro['Saga'] ?>">
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-9">
          <div class="form-group">
            <label>Modificar género</label>
            <input name="genero" type="text" class="form-control" value="<?= $libro['Genero'] ?>">
          </div>
        </div>
      </div>

      <button type="submit" class="btn btn-primary mt-2">Modificar</button>
    </form>
  <?php else: ?>
    <p>No tienes permisos suficientes</p>
  <?php endif; ?>
</div>