<?php require_once("templates/header.phtml") ?>

<?php if($verify):?>
    <?php require_once("templates/formLibro.phtml") ?>
<?php endif ?>

<div class="form-container">
    <form action="agregarLibro" method="POST" class="my-4">
        <div class="row">
            <div class="col-9">
                <div class="form-group">
                    <label>Autor:</label>
                    <select name="id_autor" id="">
                        <option value="">Elegir</option>
                        <?php foreach ($autores as $autor): ?>
                            <option value="<?= $autor->id_autor ?>"> <?= $autor->Nombre ?> </option>
                        <?php endforeach ?>
                    </select>
                </div>
            </div>
        </div>

        <div class="form-group">
            <label>Título:</label>
            <input type="text" name="Titulo">
        </div>

        <div class="form-group">
            <label>Saga:</label>
            <input type="text" name="Saga">
        </div>

        <div class="form-group">
            <label>Género:</label>
            <input type="text" name="Genero">
        </div>

        <div class="form-group">
        <label for="imagen">Link de la imagen:</label>
        <input type="text" name="imagen" id="imagen" class="form-control">
        </div>

        <button type="submit" class="btn btn-primary mt-2">Guardar</button>
    </form>
</div>