<?php require_once("templates/header.phtml") ?>

<div class="form-container">
    <form action="agregarAutor" method="POST" class="my-4">
        <div class="row">
            <div class="col-9">
                <div class="form-group">
                    <label>Nombre del Autor:</label>
                    <input name="nombre" type="text" class="form-control">
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-9">
                <div class="form-group">
                    <label>Edad del Autor:</label>
                    <input name="edad" type="text" class="form-control">
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-9">
                <div class="form-group">
                    <label>Nacionalidad del Autor:</label>
                    <input name="nacionalidad" type="text" class="form-control">
                </div>
            </div>
        </div>

        <button type="submit" class="btn btn-primary mt-2">Guardar</button>
    </form>
</div>