<?php require_once("templates/header.phtml") ?>
    
<div class="container-listado">
    <table class="table table-dark">
        <thead>
            <tr>
                <th scope="col">Nombre del Libro</th>
                <th scope="col">Ver Detalle</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($libros as $libro): ?>
                <tr>
                    <td><?= $libro->Titulo ?></td>
                    <td>
                        <a href="mostrarDetalleLibro/<?= $libro->id_libros ?>" class="btn btn-primary">Ver Detalle</a>
                    </td>
                </tr>
            <?php endforeach ?>
        </tbody>
    </table>
    <a href="showLibros" class="btn btn-primary">Back</a>
</div>